name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['1.53.0', 'nightly']
    name: Rust ${{ matrix.version }} Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
